site_name: Wikimoth
site_url: https://lpszmoths.github.io/wikimoth/
site_author: Page of Moths
site_description: Personal wiki
repo_name: Github
repo_url: https://github.com/moths/wikimoth
docs_dir: src
site_dir: docs
nav:
    - Home: index.md
    - Code:
        - Godot: code/godot.md
        - Python: code/python.md
theme:
    name: solar
    nav_style: dark
markdown_extensions:
    - toc:
        permalink: "#"

